export const createStyles = (isMobile, settings, screen) => ({
    container: {
      position: 'relative',
      width: '100%',
      height: '100vh',
      background: '#0f0f1a',
      overflow: 'hidden',
      fontFamily: "'Segoe UI', system-ui, sans-serif",
      color: '#fff',
      touchAction: 'none', // Prevent mobile browser gestures
      userSelect: 'none',
    },
    canvas: {
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
    },
    minimap: {
      position: 'absolute',
      top: isMobile ? 8 : undefined,
      bottom: isMobile ? undefined : 20,
      right: isMobile ? 8 : 20,
      border: '2px solid rgba(255,255,255,0.15)',
      borderRadius: 12,
      display: settings.showMinimap && screen === 'game' ? 'block' : 'none',
    },
    overlay: {
      position: 'absolute',
      inset: 0,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(180deg, #0f0f1a, #1a1a2e)',
      zIndex: 100,
      transition: 'opacity 0.3s',
    },
    hidden: {
      opacity: 0,
      pointerEvents: 'none',
    },
    title: {
      display: 'flex',
      alignItems: 'center',
      gap: isMobile ? 10 : 15,
      marginBottom: 8,
    },
    titleText: {
      fontSize: isMobile ? '2rem' : '3rem',
      background: 'linear-gradient(135deg, #ffd93d, #ff6b35)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
    subtitle: {
      color: '#666',
      marginBottom: isMobile ? '1rem' : '2rem',
      letterSpacing: 2,
      textTransform: 'uppercase',
      fontSize: isMobile ? '.8rem' : '1rem',
    },
    tabs: {
      display: 'flex',
      gap: isMobile ? 4 : 8,
      marginBottom: isMobile ? 15 : 25,
      flexWrap: 'wrap',
      justifyContent: 'center',
    },
    tab: (active) => ({
      padding: isMobile ? '8px 16px' : '12px 28px',
      background: active ? 'linear-gradient(135deg, #ffd93d, #ff6b35)' : 'transparent',
      border: active ? 'none' : '2px solid #2a2a3e',
      color: active ? '#000' : '#888',
      fontSize: isMobile ? '.8rem' : '.95rem',
      cursor: 'pointer',
      borderRadius: 25,
      display: 'flex',
      alignItems: 'center',
      gap: isMobile ? 4 : 8,
      fontWeight: active ? 600 : 400,
    }),
    tabIcon: {
      width: isMobile ? 14 : 18,
      height: isMobile ? 14 : 18,
    },
    content: {
      width: '100%',
      maxWidth: 900,
      padding: isMobile ? 10 : 20,
      overflowY: 'auto',
      maxHeight: isMobile ? '60vh' : 'auto',
    },
    input: {
      padding: isMobile ? '10px 16px' : '14px 20px',
      fontSize: isMobile ? '.9rem' : '1rem',
      background: 'rgba(255,255,255,0.05)',
      border: '2px solid #2a2a3e',
      borderRadius: 12,
      color: '#fff',
      width: isMobile ? 220 : 280,
      textAlign: 'center',
      outline: 'none',
    },
    classSelect: {
      display: 'flex',
      gap: isMobile ? 10 : 20,
      flexWrap: 'wrap',
      justifyContent: 'center',
      margin: isMobile ? '15px 0' : '25px 0',
    },
    classCard: (selected, color) => ({
      width: isMobile ? 150 : 200,
      padding: isMobile ? '15px 12px' : '25px 20px',
      background: 'rgba(255,255,255,0.03)',
      border: `2px solid ${selected ? color : '#2a2a3e'}`,
      borderRadius: 16,
      cursor: 'pointer',
      textAlign: 'center',
      transition: 'all 0.25s',
      boxShadow: selected ? `0 0 30px ${color}30` : 'none',
    }),
    classIcon: (color) => ({
      width: isMobile ? 50 : 70,
      height: isMobile ? 50 : 70,
      margin: '0 auto 10px',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: color,
      background: color + '20',
    }),
    classIconSvg: {
      width: isMobile ? 26 : 36,
      height: isMobile ? 26 : 36,
    },
    btn: {
      padding: isMobile ? '12px 30px' : '16px 45px',
      fontSize: isMobile ? '1rem' : '1.1rem',
      fontWeight: 600,
      border: 0,
      borderRadius: 12,
      cursor: 'pointer',
      marginTop: isMobile ? 15 : 25,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      background: 'linear-gradient(135deg, #ffd93d, #ff6b35)',
      color: '#000',
    },
    btnIcon: {
      width: isMobile ? 18 : 22,
      height: isMobile ? 18 : 22,
    },
    // HUD styles
    hud: {
      position: 'absolute',
      top: 20,
      left: 20,
      zIndex: 50,
    },
    hudPanel: {
      background: 'rgba(0,0,0,0.85)',
      backdropFilter: 'blur(10px)',
      padding: 18,
      borderRadius: 16,
      minWidth: 200,
      border: '1px solid rgba(255,255,255,0.1)',
    },
    playerHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      marginBottom: 14,
      paddingBottom: 14,
      borderBottom: '1px solid rgba(255,255,255,0.1)',
    },
    avatar: (color) => ({
      width: 46,
      height: 46,
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: color + '25',
      color: color,
    }),
    avatarIcon: {
      width: 26,
      height: 26,
    },
    statBar: {
      marginBottom: 10,
    },
    statLabel: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontSize: '.75rem',
      marginBottom: 4,
      color: '#999',
    },
    statIcon: {
      width: 14,
      height: 14,
      marginRight: 5,
    },
    barBg: {
      height: 8,
      background: 'rgba(255,255,255,0.1)',
      borderRadius: 4,
      overflow: 'hidden',
    },
    barFill: (pct, color) => ({
      height: '100%',
      width: `${pct}%`,
      background: color,
      borderRadius: 4,
      transition: 'width 0.3s',
    }),
    statsRow: {
      display: 'flex',
      gap: 16,
      fontSize: '.8rem',
      color: '#888',
      marginTop: 12,
    },
    statItem: {
      display: 'flex',
      alignItems: 'center',
      gap: 5,
    },
    // Zone indicator
    zoneIndicator: {
      position: 'absolute',
      top: 20,
      left: '50%',
      transform: 'translateX(-50%)',
      background: 'rgba(0,0,0,0.85)',
      backdropFilter: 'blur(10px)',
      padding: '10px 22px',
      borderRadius: 25,
      fontSize: '.9rem',
      zIndex: 50,
      display: 'flex',
      alignItems: 'center',
      gap: 12,
      border: '1px solid rgba(255,255,255,0.1)',
    },
    zoneIcon: (color) => ({
      width: 20,
      height: 20,
      color: color,
    }),
    zoneWarning: {
      color: '#f97316',
      fontSize: '.75rem',
      display: 'flex',
      alignItems: 'center',
      gap: 5,
    },
    // Volume control
    volumeControl: {
      position: 'absolute',
      top: 20,
      right: 20,
      zIndex: 50,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      background: 'rgba(0,0,0,0.85)',
      backdropFilter: 'blur(10px)',
      padding: '8px 14px',
      borderRadius: 25,
      border: '1px solid rgba(255,255,255,0.1)',
    },
    volumeBtn: {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      padding: 4,
      display: 'flex',
      color: '#888',
    },
    volumeIcon: {
      width: 20,
      height: 20,
    },
    volumeSlider: {
      width: 70,
    },
    // Level up popup
    levelUpPopup: {
      position: 'absolute',
      top: isMobile ? 60 : 80,
      left: '50%',
      transform: 'translateX(-50%)',
      background: 'rgba(0,0,0,0.6)',
      backdropFilter: 'blur(5px)',
      padding: isMobile ? '12px 25px' : '15px 35px',
      borderRadius: 15,
      border: '2px solid rgba(255,215,61,0.5)',
      textAlign: 'center',
      zIndex: 55,
      pointerEvents: 'none', // Don't block clicks/touches
    },
    // Controls hint
    controlsHint: {
      position: 'absolute',
      bottom: 20,
      left: 20,
      background: 'rgba(0,0,0,0.7)',
      padding: '8px 14px',
      borderRadius: 8,
      fontSize: '.75rem',
      color: '#666',
      zIndex: 50,
    },
    // Connection status
    connection: (connected) => ({
      position: 'absolute',
      top: isMobile ? 114 : 10,
      right: isMobile ? 8 : 10,
      padding: '3px 8px',
      borderRadius: 15,
      fontSize: '.65rem',
      zIndex: 50,
      display: 'flex',
      alignItems: 'center',
      gap: 4,
      background: 'rgba(0,0,0,0.5)',
      color: connected ? '#4ade80' : '#f87171',
    }),
    connDot: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      background: 'currentColor',
    },
    // Tutorial styles
    tutorial: {
      maxWidth: 700,
      textAlign: 'left',
      padding: isMobile ? '0 10px' : 0,
    },
    tutorialSection: {
      marginBottom: isMobile ? 20 : 28,
    },
    tutorialTitle: {
      color: '#ffd93d',
      marginBottom: isMobile ? 8 : 12,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      fontSize: isMobile ? '.95rem' : '1.1rem',
    },
    tutorialIcon: {
      width: isMobile ? 18 : 22,
      height: isMobile ? 18 : 22,
    },
    tutorialText: {
      color: '#999',
      lineHeight: 1.7,
      fontSize: isMobile ? '.85rem' : '1rem',
    },
    key: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: isMobile ? 28 : 32,
      padding: isMobile ? '3px 8px' : '4px 10px',
      background: '#2a2a3e',
      borderRadius: 6,
      fontFamily: 'monospace',
      fontSize: isMobile ? '.75rem' : '.85rem',
      color: '#fff',
      marginRight: 8,
    },
    zoneList: {
      display: 'grid',
      gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, 1fr)',
      gap: isMobile ? 8 : 12,
      marginTop: 15,
    },
    zoneItem: (color) => ({
      padding: isMobile ? 10 : 14,
      background: 'rgba(255,255,255,0.03)',
      borderRadius: 10,
      borderLeft: `4px solid ${color}`,
      display: 'flex',
      alignItems: 'flex-start',
      gap: isMobile ? 8 : 12,
    }),
    zoneItemIcon: {
      width: isMobile ? 20 : 24,
      height: isMobile ? 20 : 24,
      flexShrink: 0,
    },
    // Settings styles
    settingsContent: {
      maxWidth: 380,
      padding: isMobile ? '0 10px' : 0,
    },
    settingRow: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: isMobile ? 12 : 16,
      background: 'rgba(255,255,255,0.03)',
      borderRadius: 12,
      marginBottom: isMobile ? 8 : 12,
    },
    settingLabel: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      fontSize: isMobile ? '.85rem' : '.95rem',
    },
    settingIcon: {
      width: 20,
      height: 20,
      opacity: 0.7,
    },
    toggle: (on) => ({
      width: 48,
      height: 26,
      background: on ? '#4ade80' : '#2a2a3e',
      borderRadius: 13,
      position: 'relative',
      cursor: 'pointer',
      transition: 'background 0.2s',
    }),
    toggleKnob: (on) => ({
      position: 'absolute',
      width: 20,
      height: 20,
      background: '#fff',
      borderRadius: '50%',
      top: 3,
      left: on ? 25 : 3,
      transition: 'left 0.2s',
    }),
    // Death screen styles
    deathStats: {
      display: 'flex',
      gap: 30,
      margin: '25px 0',
    },
    deathStat: {
      textAlign: 'center',
    },
    deathValue: {
      fontSize: '2rem',
      fontWeight: 700,
      color: '#ffd93d',
    },
    deathLabel: {
      fontSize: '.8rem',
      color: '#888',
      marginTop: 5,
    },
    // Mobile touch controls
    touchControls: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 200,
      pointerEvents: 'none',
      zIndex: 60,
    },
    joystickArea: {
      position: 'absolute',
      bottom: 50,
      left: 30,
      width: 120,
      height: 120,
      pointerEvents: 'auto',
      touchAction: 'none',
    },
    joystickBase: {
      width: 120,
      height: 120,
      borderRadius: '50%',
      background: 'rgba(255,255,255,0.1)',
      border: '3px solid rgba(255,255,255,0.3)',
      position: 'relative',
    },
    joystickKnob: {
      width: 50,
      height: 50,
      borderRadius: '50%',
      background: 'rgba(255,255,255,0.5)',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      transition: 'none',
    },
    actionButtons: {
      position: 'absolute',
      bottom: 30,
      right: 30,
      display: 'flex',
      flexDirection: 'column',
      gap: 15,
      pointerEvents: 'auto',
    },
    actionButton: (color) => ({
      width: 70,
      height: 70,
      borderRadius: '50%',
      background: `linear-gradient(135deg, ${color}, ${color}aa)`,
      border: '3px solid rgba(255,255,255,0.4)',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      color: '#fff',
      fontSize: '0.75rem',
      fontWeight: 'bold',
      textShadow: '0 1px 2px rgba(0,0,0,0.5)',
      cursor: 'pointer',
      touchAction: 'manipulation',
      userSelect: 'none',
    }),
    actionButtonIcon: {
      width: 24,
      height: 24,
    },
    // Mobile-specific style overrides
    mobileHud: {
      position: 'absolute',
      top: 8,
      left: 8,
      zIndex: 50,
    },
    mobileHudPanel: {
      background: 'rgba(0,0,0,0.35)',
      backdropFilter: 'blur(8px)',
      padding: 8,
      borderRadius: 10,
      minWidth: 130,
      border: '1px solid rgba(255,255,255,0.06)',
    },
    mobilePlayerHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      marginBottom: 6,
      paddingBottom: 6,
      borderBottom: '1px solid rgba(255,255,255,0.08)',
    },
    mobileAvatar: (color) => ({
      width: 28,
      height: 28,
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: color + '20',
      color: color,
    }),
    mobileAvatarIcon: {
      width: 16,
      height: 16,
    },
    mobileZoneIndicator: {
      position: 'absolute',
      top: 95,
      left: 10,
      background: 'rgba(0,0,0,0.75)',
      backdropFilter: 'blur(10px)',
      padding: '4px 10px',
      borderRadius: 12,
      fontSize: '.7rem',
      zIndex: 50,
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      border: '1px solid rgba(255,255,255,0.1)',
    },
    // Returning player screen
    returningCard: {
      background: 'rgba(255,255,255,0.03)',
      border: '2px solid #2a2a3e',
      borderRadius: 20,
      padding: isMobile ? 20 : 30,
      maxWidth: 400,
      width: '90%',
      textAlign: 'center',
    },
    returningAvatar: (color) => ({
      width: isMobile ? 80 : 100,
      height: isMobile ? 80 : 100,
      borderRadius: '50%',
      margin: '0 auto 20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: color + '25',
      color: color,
      border: `3px solid ${color}`,
    }),
    returningAvatarIcon: {
      width: isMobile ? 45 : 55,
      height: isMobile ? 45 : 55,
    },
    returningName: {
      fontSize: isMobile ? '1.5rem' : '1.8rem',
      fontWeight: 700,
      marginBottom: 5,
    },
    returningStats: {
      display: 'flex',
      justifyContent: 'center',
      gap: isMobile ? 20 : 30,
      margin: '20px 0',
      flexWrap: 'wrap',
    },
    returningStat: {
      textAlign: 'center',
    },
    returningStatValue: {
      fontSize: isMobile ? '1.3rem' : '1.5rem',
      fontWeight: 700,
      color: '#ffd93d',
    },
    returningStatLabel: {
      fontSize: '.75rem',
      color: '#888',
      marginTop: 4,
    },
    returningButtons: {
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      marginTop: 25,
    },
    secondaryBtn: {
      padding: isMobile ? '10px 20px' : '12px 30px',
      fontSize: isMobile ? '.9rem' : '1rem',
      fontWeight: 500,
      border: '2px solid #2a2a3e',
      borderRadius: 12,
      cursor: 'pointer',
      background: 'transparent',
      color: '#888',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    // Skin selector
    skinSelector: {
      marginTop: 20,
      padding: 15,
      background: 'rgba(0,0,0,0.3)',
      borderRadius: 12,
    },
    skinSelectorTitle: {
      fontSize: '.85rem',
      color: '#888',
      marginBottom: 12,
      display: 'flex',
      alignItems: 'center',
      gap: 8,
    },
    skinGrid: {
      display: 'flex',
      gap: 10,
      flexWrap: 'wrap',
      justifyContent: 'center',
    },
    skinOption: (selected, color, locked) => ({
      width: isMobile ? 50 : 60,
      height: isMobile ? 50 : 60,
      borderRadius: 12,
      background: locked ? 'rgba(255,255,255,0.02)' : color + '20',
      border: `2px solid ${selected ? color : locked ? '#1a1a2e' : '#2a2a3e'}`,
      cursor: locked ? 'not-allowed' : 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      opacity: locked ? 0.4 : 1,
      position: 'relative',
      transition: 'all 0.2s',
    }),
    skinOptionInner: (color) => ({
      width: isMobile ? 30 : 36,
      height: isMobile ? 30 : 36,
      borderRadius: '50%',
      background: color,
    }),
    skinLock: {
      position: 'absolute',
      bottom: -5,
      right: -5,
      background: '#1a1a2e',
      borderRadius: '50%',
      width: 18,
      height: 18,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '10px',
    },
    skinTooltip: {
      position: 'absolute',
      bottom: '100%',
      left: '50%',
      transform: 'translateX(-50%)',
      background: 'rgba(0,0,0,0.95)',
      padding: '6px 10px',
      borderRadius: 6,
      fontSize: '.7rem',
      whiteSpace: 'nowrap',
      marginBottom: 5,
      pointerEvents: 'none',
    },
    // In-game skin modal
    modal: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      background: 'rgba(15,15,26,0.98)',
      border: '2px solid #2a2a3e',
      borderRadius: 20,
      padding: isMobile ? 20 : 30,
      zIndex: 200,
      maxWidth: 400,
      width: '90%',
    },
    modalBackdrop: {
      position: 'absolute',
      inset: 0,
      background: 'rgba(0,0,0,0.7)',
      zIndex: 199,
    },
    modalTitle: {
      fontSize: '1.3rem',
      fontWeight: 600,
      marginBottom: 20,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
    },
    modalClose: {
      position: 'absolute',
      top: 15,
      right: 15,
      background: 'none',
      border: 'none',
      color: '#888',
      cursor: 'pointer',
      fontSize: '1.5rem',
    },
    // Loading screen
    loadingText: {
      color: '#888',
      fontSize: '1.1rem',
    },
    spinner: {
      width: 40,
      height: 40,
      border: '3px solid #2a2a3e',
      borderTopColor: '#ffd93d',
      borderRadius: '50%',
      animation: 'spin 1s linear infinite',
      marginBottom: 20,
    },
});