/**
 * Client-side utilities for agent activity logging and RAG chunk creation
 * Used in admin panel when projects are saved
 */

import { collection, addDoc, doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../config/firebase';

// Activity types
export const ACTIVITY_TYPES = {
  BLOG_GENERATED: 'blog_generated',
  MOLTBOOK_POST: 'moltbook_post',
  MOLTBOOK_COMMENT: 'moltbook_comment',
  MOLTBOOK_UPVOTE: 'moltbook_upvote',
  PROJECT_UPDATED: 'project_updated',
  PROJECT_CREATED: 'project_created',
  RAG_CHUNK_CREATED: 'rag_chunk_created',
  RAG_CHUNK_UPDATED: 'rag_chunk_updated',
  FITNESS_SYNCED: 'fitness_synced',
  CHAT_ANSWERED: 'chat_answered'
};

/**
 * Log an agent activity to Firestore
 */
export async function logAgentActivity({
  type,
  title,
  description = null,
  reasoning = null,
  metadata = {},
  source = 'admin'
}) {
  try {
    const activityRef = collection(db, 'agent_activity');
    const docRef = await addDoc(activityRef, {
      type,
      title,
      description,
      reasoning,
      metadata,
      source,
      timestamp: serverTimestamp()
    });
    console.log(`[activity] Logged: ${type} - ${title}`);
    return docRef.id;
  } catch (error) {
    console.error('[activity] Failed to log:', error);
    throw error;
  }
}

/**
 * Create or update a RAG chunk for a project
 * Automatically logs the activity
 */
export async function createProjectChunk(project) {
  // Build searchable content
  const contentParts = [
    `Project: ${project.title}`,
    project.tagline,
    project.description,
    project.fullDescription,
    project.tech?.length ? `Tech stack: ${project.tech.join(', ')}` : null,
    project.highlights?.length ? `Key features: ${project.highlights.join('. ')}` : null
  ].filter(Boolean);

  const content = contentParts.join('. ');

  const chunkId = `project-${project.id}`;
  const chunk = {
    id: chunkId,
    content,
    metadata: {
      type: 'project',
      projectId: project.id,
      title: project.title,
      url: project.liveUrl || null,
      github: project.githubUrl || null,
      tags: project.tech || [],
      category: project.category || null
    },
    embedding: null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  };

  try {
    // Upsert the chunk
    const chunkRef = doc(db, 'rag_chunks', chunkId);
    await setDoc(chunkRef, chunk, { merge: true });

    // Log the activity
    await logAgentActivity({
      type: ACTIVITY_TYPES.RAG_CHUNK_CREATED,
      title: 'Updated knowledge base',
      description: `Indexed project: ${project.title}`,
      reasoning: `Project "${project.title}" was saved, so I updated the RAG knowledge base to ensure the chatbot has accurate information about it.`,
      metadata: { 
        projectId: project.id, 
        chunkId,
        contentLength: content.length 
      },
      source: 'admin'
    });

    console.log(`[rag] Created/updated chunk: ${chunkId}`);
    return chunk;
  } catch (error) {
    console.error('[rag] Failed to create chunk:', error);
    throw error;
  }
}

/**
 * Create a RAG chunk for a blog post
 */
export async function createBlogChunk(post) {
  const content = [
    `Blog post: ${post.title}`,
    post.excerpt,
    post.content?.substring(0, 2000) // First 2000 chars of content
  ].filter(Boolean).join('. ');

  const chunkId = `blog-${post.id || post.slug}`;
  const chunk = {
    id: chunkId,
    content,
    metadata: {
      type: 'blog',
      postId: post.id,
      slug: post.slug,
      title: post.title,
      tags: post.tags || [],
      autoGenerated: post.autoGenerated || false
    },
    embedding: null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  };

  try {
    const chunkRef = doc(db, 'rag_chunks', chunkId);
    await setDoc(chunkRef, chunk, { merge: true });
    console.log(`[rag] Created/updated blog chunk: ${chunkId}`);
    return chunk;
  } catch (error) {
    console.error('[rag] Failed to create blog chunk:', error);
    throw error;
  }
}