// Zone tile colors [light, dark]
export const COLORS = {
  sanctuary: ['#3d7a3d', '#2d6a2d'],
  meadow: ['#4a8b3d', '#3a7b2d'],
  forest: ['#2d5a27', '#234d1f'],
  volcanic: ['#4a3232', '#3d2828'],
  frozen: ['#4a5a6a', '#3a4a5a'],
  abyss: ['#1a1a2e', '#12121f'],
  crystal_caves: ['#5a3a5a', '#4a2a4a'],
  dungeon: ['#1a1414', '#120e0e'],
  
  enemy: {
    slime: '#4ade80',
    bat: '#a855f7',
    skeleton: '#e5e5e5',
    ghost: '#94a3b8',
    golem: '#78716c',
    spider: '#1a1a1a',
    necromancer: '#581c87',
    fireElemental: '#f97316',
    iceElemental: '#06b6d4',
    boss_slime: '#22c55e',
    boss_dragon: '#dc2626',
  },
};

export const DEFAULT_CLASSES = {
  pyromancer: {
    id: 'pyromancer',
    name: 'Pyromancer',
    color: '#ff6b35',
    description: 'Fire master. High burst damage.',
    dash: 'Fire Dash',
    ultimate: 'Meteor Strike',
    baseHealth: 80,
    baseSpeed: 160,
  },
  cryomancer: {
    id: 'cryomancer',
    name: 'Cryomancer',
    color: '#4ecdc4',
    description: 'Ice wizard. Crowd control specialist.',
    dash: 'Frost Step',
    ultimate: 'Ice Nova',
    baseHealth: 90,
    baseSpeed: 150,
  },
  arcanist: {
    id: 'arcanist',
    name: 'Arcanist',
    color: '#9b5de5',
    description: 'Arcane power. Balanced with AOE.',
    dash: 'Blink',
    ultimate: 'Arcane Barrage',
    baseHealth: 100,
    baseSpeed: 140,
  },
  voidlord: {
    id: 'voidlord',
    name: 'Void Lord',
    color: '#1a0a2e',
    secondaryColor: '#ff00ff',
    description: 'Master of the void. Admin only.',
    dash: 'Void Shift',
    ultimate: 'Void Rift',
    baseHealth: 200,
    baseSpeed: 280,
    isAdmin: true,
    hidden: true, // Don't show in normal class selection
  },
};

export const DEFAULT_SKINS = [
  // ============ PYROMANCER SKINS ============
  { 
    id: 'pyromancer_default', 
    class: 'pyromancer', 
    name: 'Apprentice', 
    color: '#ff6b35', 
    requiredXp: 0,
    description: 'A novice flame wielder',
  },
  { 
    id: 'pyromancer_ember', 
    class: 'pyromancer', 
    name: 'Ember Mage', 
    color: '#f97316', 
    requiredXp: 2000,
    trail: { color: '#ff6b35', particles: 2, size: 3 },
    description: 'Leaves embers in your wake',
  },
  { 
    id: 'pyromancer_inferno', 
    class: 'pyromancer', 
    name: 'Inferno Master', 
    color: '#dc2626', 
    requiredXp: 8000,
    trail: { color: '#ff4500', particles: 3, size: 4 },
    aura: { color: '#ff6b35', radius: 25, pulse: true },
    description: 'Surrounded by intense heat',
  },
  { 
    id: 'pyromancer_phoenix', 
    class: 'pyromancer', 
    name: 'Phoenix Lord', 
    color: '#fbbf24', 
    secondaryColor: '#ff6b35',
    requiredXp: 25000,
    trail: { color: '#fbbf24', particles: 4, size: 5, rainbow: false },
    aura: { color: '#ff8c00', radius: 35, pulse: true },
    wings: true,
    projectileEffect: 'fire_wings',
    description: 'Reborn from the ashes',
  },
  { 
    id: 'pyromancer_shadow', 
    class: 'pyromancer', 
    name: 'Shadow Flame', 
    color: '#7c3aed', 
    secondaryColor: '#ff00ff',
    requiredXp: 50000,
    trail: { color: '#7c3aed', particles: 5, size: 4 },
    aura: { color: '#9333ea', radius: 30, pulse: true },
    projectileEffect: 'shadow',
    description: 'Dark fire consumes all',
  },
  { 
    id: 'pyromancer_hellfire', 
    class: 'pyromancer', 
    name: 'Hellfire Incarnate', 
    color: '#450a0a', 
    secondaryColor: '#dc2626',
    requiredXp: -1, // Not yet obtainable
    trail: { color: '#dc2626', particles: 6, size: 6 },
    aura: { color: '#b91c1c', radius: 40, pulse: true },
    wings: true,
    horns: true,
    projectileEffect: 'hellfire',
    description: 'COMING SOON - Defeat the Infernal Dragon',
    locked: true,
  },
  
  // ============ CRYOMANCER SKINS ============
  { 
    id: 'cryomancer_default', 
    class: 'cryomancer', 
    name: 'Apprentice', 
    color: '#4ecdc4', 
    requiredXp: 0,
    description: 'A student of frost magic',
  },
  { 
    id: 'cryomancer_frost', 
    class: 'cryomancer', 
    name: 'Frost Weaver', 
    color: '#06b6d4', 
    requiredXp: 2000,
    trail: { color: '#67e8f9', particles: 2, size: 3 },
    description: 'Leaves frost in your path',
  },
  { 
    id: 'cryomancer_glacier', 
    class: 'cryomancer', 
    name: 'Glacier Knight', 
    color: '#0284c7', 
    requiredXp: 8000,
    trail: { color: '#38bdf8', particles: 3, size: 4 },
    aura: { color: '#0ea5e9', radius: 25, pulse: false },
    iceArmor: true,
    description: 'Encased in living ice',
  },
  { 
    id: 'cryomancer_blizzard', 
    class: 'cryomancer', 
    name: 'Blizzard King', 
    color: '#e0f2fe', 
    secondaryColor: '#0ea5e9',
    requiredXp: 25000,
    trail: { color: '#ffffff', particles: 5, size: 5, snowflakes: true },
    aura: { color: '#bae6fd', radius: 35, pulse: true },
    crown: true,
    projectileEffect: 'blizzard',
    description: 'Commands the frozen storms',
  },
  { 
    id: 'cryomancer_void', 
    class: 'cryomancer', 
    name: 'Void Ice', 
    color: '#1e1b4b', 
    secondaryColor: '#4f46e5',
    requiredXp: 50000,
    trail: { color: '#6366f1', particles: 4, size: 4 },
    aura: { color: '#4338ca', radius: 30, pulse: true },
    projectileEffect: 'void_frost',
    description: 'Cold as the endless void',
  },
  { 
    id: 'cryomancer_absolute', 
    class: 'cryomancer', 
    name: 'Absolute Zero', 
    color: '#ffffff', 
    secondaryColor: '#0ea5e9',
    requiredXp: -1, // Not yet obtainable
    trail: { color: '#ffffff', particles: 6, size: 6, snowflakes: true },
    aura: { color: '#ffffff', radius: 45, pulse: true },
    iceArmor: true,
    crown: true,
    projectileEffect: 'absolute',
    description: 'COMING SOON - Defeat the Frost Wyrm 10 times',
    locked: true,
  },
  
  // ============ ARCANIST SKINS ============
  { 
    id: 'arcanist_default', 
    class: 'arcanist', 
    name: 'Apprentice', 
    color: '#9b5de5', 
    requiredXp: 0,
    description: 'A student of the arcane',
  },
  { 
    id: 'arcanist_mystic', 
    class: 'arcanist', 
    name: 'Mystic Sage', 
    color: '#a855f7', 
    requiredXp: 2000,
    trail: { color: '#c084fc', particles: 2, size: 3 },
    description: 'Channels ancient wisdom',
  },
  { 
    id: 'arcanist_archmage', 
    class: 'arcanist', 
    name: 'Archmage', 
    color: '#7c3aed', 
    requiredXp: 8000,
    trail: { color: '#a78bfa', particles: 3, size: 4 },
    aura: { color: '#8b5cf6', radius: 25, pulse: true },
    floatingRunes: true,
    description: 'Master of magical arts',
  },
  { 
    id: 'arcanist_celestial', 
    class: 'arcanist', 
    name: 'Celestial', 
    color: '#fcd34d', 
    secondaryColor: '#f59e0b',
    requiredXp: 25000,
    trail: { color: '#fbbf24', particles: 4, size: 5, stars: true },
    aura: { color: '#fde047', radius: 35, pulse: true },
    halo: true,
    projectileEffect: 'celestial',
    description: 'Touched by the stars',
  },
  { 
    id: 'arcanist_cosmic', 
    class: 'arcanist', 
    name: 'Cosmic Entity', 
    color: '#1e1b4b', 
    secondaryColor: '#c084fc',
    requiredXp: 50000,
    trail: { color: '#a855f7', particles: 5, size: 4, stars: true },
    aura: { color: '#7c3aed', radius: 30, pulse: true },
    floatingRunes: true,
    projectileEffect: 'cosmic',
    description: 'One with the universe',
  },
  { 
    id: 'arcanist_chrono', 
    class: 'arcanist', 
    name: 'Chronomancer', 
    color: '#0891b2', 
    secondaryColor: '#fbbf24',
    requiredXp: -1, // Not yet obtainable
    trail: { color: '#fbbf24', particles: 6, size: 6, timeEcho: true },
    aura: { color: '#06b6d4', radius: 40, pulse: true },
    halo: true,
    floatingRunes: true,
    clockwork: true,
    projectileEffect: 'temporal',
    description: 'COMING SOON - Beat all dungeons in under 5 minutes',
    locked: true,
  },
  
  // ============ VOIDLORD SKINS (Admin) ============
  { 
    id: 'voidlord_default', 
    class: 'voidlord', 
    name: 'Void Lord', 
    color: '#1a0a2e', 
    secondaryColor: '#ff00ff',
    requiredXp: 0,
    trail: { color: '#ff00ff', particles: 4, size: 4 },
    aura: { color: '#9333ea', radius: 40, pulse: true },
    description: 'Master of the void',
  },
  { 
    id: 'voidlord_ascended', 
    class: 'voidlord', 
    name: 'Ascended', 
    color: '#ff00ff', 
    secondaryColor: '#ffffff',
    requiredXp: 0,
    trail: { color: '#ffffff', particles: 6, size: 6 },
    aura: { color: '#ff00ff', radius: 50, pulse: true },
    wings: true,
    halo: true,
    description: 'Beyond mortal comprehension',
  },
  { 
    id: 'voidlord_oblivion', 
    class: 'voidlord', 
    name: 'Oblivion', 
    color: '#000000', 
    secondaryColor: '#dc2626',
    requiredXp: 0,
    trail: { color: '#dc2626', particles: 8, size: 5 },
    aura: { color: '#450a0a', radius: 60, pulse: true },
    wings: true,
    horns: true,
    projectileEffect: 'oblivion',
    description: 'The end of all things',
  },
];

// Server URL - set REACT_APP_GAME_SERVER in your .env file
export const SERVER_URL = process.env.REACT_APP_GAME_SERVER || 'http://localhost:3001';